<?php

	/**
	 * GGN DPO Device
	 *
	 * @version 1.2
	 * @update 150910.0900
	 * @Require Gougnon Framework
	*/




/*
	Nom de l'espace
*/
namespace GGN\GeoLocation\Country\CI;
	



	if(!class_exists('GGN\GeoLocation\Country\CI\Load')){
			
		Class Load{
				
			const NAME = 'Gougnon Geo-Localisation : CI';
			
			const VERSION = '0.1';
			
			const UPDATE = '160218.0852';


			var $Cities = [

					"abengourou"
					,"abidjan"
					,"abidjan - yopougon"
					,"abidjan - abobo"
					,"abidjan - cocody"
					,"abidjan - marcory"
					,"abidjan - treichville"
					,"abidjan - koumassi"
					,"abidjan - plateau"
					,"abidjan - port-bouet"
					,"abidjan - adjamé"
					,"abidjan - attécoubé"
					,"aboisso"
					,"aboisso-comoe"
					,"abongoua"
					,"aboude"
					,"aby"
					,"addah-bahuma"
					,"adiake"
					,"adjouan"
					,"adzope"
					,"affalikro"
					,"affery"
					,"affienou"
					,"afotobo"
					,"agban"
					,"agbaou"
					,"agbossou"
					,"agboville"
					,"agnia"
					,"agnibilekro"
					,"agou"
					,"aheoua"
					,"ahizabre"
					,"ahouabo"
					,"ahoue"
					,"ahoutoue"
					,"aka n'guessankro"
					,"akekro"
					,"akoboissue"
					,"akohe n'denou"
					,"akoupe"
					,"akoure"
					,"akpessokro"
					,"akradio"
					,"akridou-lade"
					,"alepe"
					,"amelekia"
					,"anandakouadiokro"
					,"anaguie"
					,"ande"
					,"ando-kekrenou"
					,"angoda"
					,"aniassue"
					,"anno"
					,"anoumaba"
					,"anyama"
					,"apouesso"
					,"
					apropronou"
					,"armebe"
					,"arraguie"
					,"arrah"
					,"assandre"
					,"assie koumassi"
					,"assikoi"
					,"assinie"
					,"assouba"
					,"assounvoue"
					,"assrikro"
					,"assuefri"
					,"attiegouakro"
					,"attiekoi"
					,"attinguie"
					,"attobrou"
					,"avagou"
					,"ayame"
					,"ayaou-sokpa"
					,"azaguie"
					,"bacon"
					,"bakanda"
					,"bakanou"
					,"bako"
					,"bakro"
					,"banandje"
					,"bandakagni-sokoura"
					,"bangolo"
					,"banguie"
					,"bania"
					,"bassam"
					,"bassawa"
					,"bayota/ logouata/ nikeide"
					,"beago"
					,"becedi brignan"
					,"becouefin"
					,"bediala/banoufla"
					,"belleville"
					,"benganssou"
					,"beoumi"
					,"bettie"
					,"biankouma"
					,"bianouan"
					,"biasso"
					,"biebi"
					,"bin-houien"
					,"binao"
					,"bingerville"
					,"binzra"
					,"bizeraguhe"
					,"blessegue"
					,"blibouda"
					,"blolequin"
					,"bocanda"
					,"bodo"
					,"bogouine"
					,"boguedia"
					,"bokala"
					,"boli kouadiokro"
					,"bolona"
					,"bomizambo"
					,"bondoukou"
					,"bongo saph"
					,"bongouanou"
					,"bonguera"
					,"bonieredougou"
					,"bonon"
					,"bonoua"
					,"bonoufla"
					,"borotou"
					,"botinde"
					,"bouadikro"
					,"bouafle"
					,"bouake"
					,"bouape"
					,"bouayaokro"
					,"bouboury"
					,"boudepe"
					,"bouna"
					,"bounafla"
					,"boundiali"
					,"boussoukro/ kodimasso"
					,"bozi"
					,"braffedon"
					,"bregbo"
					,"brihi"
					,"brou akpaoussou"
					,"brozan"
					,"buyo"
					,"cechi"
					,"chc-cavaly"
					,"cosrou"
					,"cs koro"
					,"dabakala"
					,"dabou"
					,"dagbego"
					,"dairo"
					,"dakourytrochon"
					,"daloa"
					,"dame"
					,"danane"
					,"danguira"
					,"daoukro"
					,"debete"
					,"debrimou"
					,"diabo"
					,"diacohou"
					,"diamankani"
					,"diamba"
					,"diangobo"
					,"dianra"
					,"diarabana"
					,"diawala"
					,"didievi"
					,"didoko"
					,"diogonefla"
					,"diekadiokro"
					,"dignango"
					,"dikodougou"
					,"dimbokro"
					,"divo"
					,"djebonoua"
					,"djekanou"
					,"domolon"
					,"doropo"
					,"douasso"
					,"dougbafla"
					,"doukouya"
					,"duekoue"
					,"ebilassokro"
					,"eboinda"
					,"eboue"
					,"ehania"
					,"elibou"
					,"ettokro"
					,"facobly"
					,"ferentela"
					,"ferkessedougou"
					,"foulakiedougou"
					,"fresco"
					,"fronan"
					,"gabia"
					,"gabiadji"
					,"gadouan"
					,"gagnoa"
					,"galobouo"
					,"ganwe"
					,"gbagbam"
					,"gbeleban"
					,"gboguhe"
					,"gbon"
					,"gnatroa"
					,"gohitafla"
					,"gomon"
					,"gonate"
					,"goudi"
					,"goumere"
					,"gouromiankro"
					,"grabo"
					,"grand-akouzin"
					,"grand-bassam"
					,"grand-beredy"
					,"grand-jacques"
					,"grand- lahou"
					,"grand-morie"
					,"grand-yapo"
					,"grand-zattry"
					,"grobiassoume"
					,"guepahouo"
					,"guessabo"
					,"gueyo"
					,"guiberoua"
					,"guiembe"
					,"guiende"
					,"guiglo"
					,"guilehiry"
					,"guinteguela"
					,"guitry"
					,"hermankono garo"
					,"hermankono-dies"
					,"hire"
					,"iboke"
					,"irobo"
					,"iroporia"
					,"issia"
					,"jacqueville"
					,"kahanso"
					,"kami"
					,"kanakono"
					,"kani"
					,"kaniasso"
					,"karakoro"
					,"kassere"
					,"katiola"
					,"kimoukro"
					,"klotou"
					,"koffi ahoussoukro"
					,"koffikro-affima"
					,"kokolopozo"
					,"kokoumbo"
					,"kolia"
					,"komborodougou"
					,"konan kokorekro"
					,"konefla"
					,"kong"
					,"kongoue"
					,"korhogo"
					,"koro"
					,"kossou"
					,"kotobi"
					,"kouamefla"
					,"kouassi-datekro"
					,"kouassi-kouassikro"
					,"kouetinfla"
					,"kouibly"
					,"koukourandoumi"
					,"koumbala"
					,"koun-abroson"
					,"koun-fao"
					,"kounahiri"
					,"kouto"
					,"kregbe"
					,"krindjabo"
					,"lakota"
					,"laoguie"
					,"loboville"
					,"logbakro"
					,"logouale"
					,"lolobo"
					,"lopou"
					,"louha"
					,"loviguie"
					,"luehouan"
					,"luenoufla"
					,"m'bahiakro"
					,"m'batto"
					,"m'bengue"
					,"mabehiri"
					,"madinani"
					,"mafere"
					,"mahapleu"
					,"makey"
					,"mama"
					,"maminigui"
					,"man"
					,"mandougou"
					,"manfla"
					,"mankono"
					,"mayo"
					,"meagui"
					,"memni"
					,"minignan"
					,"moape"
					,"montezo"
					,"mopoyem/bodou"
					,"morokro"
					,"morondo"
					,"motebe"
					,"n'djem"
					,"n'douci"
					,"n'gattadolikro"
					,"n'gouimbo"
					,"n'guessan-pokoukro"
					,"n'zianoua"
					,"n'zikro"
					,"nafoun"
					,"nambezaria"
					,"nangbo-dongbo"
					,"napieledougou"
					,"nassian"
					,"niable"
					,"niakaramandougou"
					,"niambrun"
					,"niangbo"
					,"nielle"
					,"niofoin"
					,"noe"
					,"nouamou"
					,"odienne"
					,"offa"
					,"okromoudou"
					,"ono"
					,"opouyo"
					,"orbaff"
					,"ores-krobou"
					,"ottawa"
					,"ouangolodougou"
					,"ouaninou"
					,"ouara"
					,"ouelle"
					,"oume"
					,"ouragahio"
					,"padiegnan"
					,"pakouabo"
					,"papara"
					,"para"
					,"parhadi"
					,"podiagouine"
					,"pogo"
					,"prikro"
					,"raviart"
					,"rolanfla"
					,"rubino"
					,"sahabo"
					,"sahue"
					,"saioua"
					,"sakassou"
					,"samatiguila"
					,"samo"
					,"san-pedro"
					,"sandegue"
					,"sanhala"
					,"sankadiokro"
					,"sasako-begniny"
					,"sassandra"
					,"satama-sokoro"
					,"satama-sokoura"
					,"seguela"
					,"seguelon"
					,"seman"
					,"serebou comoe"
					,"seydougou"
					,"siempurgo"
					,"sifie"
					,"sikensi"
					,"sinematiali"
					,"sinfra"
					,"sipilou"
					,"sirasso"
					,"sogb"
					,"soko"
					,"songon"
					,"sogon-agban"
					,"songon-dagbe"
					,"songon-kassemble"
					,"soubre"
					,"soungassou"
					,"sucaf 1 et 2"
					,"taabo"
					,"tabagne"
					,"tabou"
					,"tafire"
					,"tagoura"
					,"tai"
					,"takikro"
					,"talahini"
					,"tanda"
					,"tanguelan"
					,"tankesse"
					,"tehiri"
					,"tengrela"
					,"tiapoum"
					,"tiassale"
					,"tie-n'diekro"
					,"tiebissou"
					,"tiegba"
					,"tieme"
					,"tiemelekro"
					,"tieningboue"
					,"tienko"
					,"tieny-seably"
					,"timelekro"
					,"tioroniaradougou"
					,"tonla"
					,"tortiya"
					,"touadji 1"
					,"touba"
					,"toukouzou"
					,"toulepleu"
					,"toumanguie"
					,"toumbokro"
					,"toumodi"
					,"toumodi-sakassou"
					,"toupah"
					,"touvre"
					,"transua"
					,"vavoua"
					,"vitre 1 et 2"
					,"wora"
					,"worofla"
					,"yabayo"
					,"yacolidabouo"
					,"yakasse"
					,"yakasse-attobrou"
					,"yakasse-feyasse"
					,"yakasse-me"
					,"yakassebini"
					,"yamoussoukro"
					,"yaobou"
					,"yaokro"
					,"yassap"
					,"yocoboue"
					,"yorobodi"
					,"zaakro"
					,"zagne"
					,"zagoreta"
					,"zahala"
					,"zaibo"
					,"zalihouan"
					,"zamaka"
					,"zambakro"
					,"zanfouenou"
					,"zangue"
					,"zaranou"
					,"zaroko/bouakakro"
					,"zatta"
					,"zeaglo"
					,"zego"
					,"zikisso"
					,"zinzenou"
					,"zouan-hounien"
					,"zoukougbeu"
					,"zro"
					,"zuenoula"
			];

			

		} // Class 'Invoke'


	} // If class exists 'Invoke'


